#!/usr/bin/env bash

bold=$(tput bold)
teal=$(tput setaf 14)
normal=$(tput sgr0)

echo -n Generating tests...
./bin/generateTests.js
echo done

rm -f results.md
echo '| runner | real | user | system |' > results.md
echo '| ------ | ----:| ----:| ------:|' >> results.md

echo "${bold}${teal}************* Jest *************${normal}"
echo "${bold}Jest all tests...${normal}"
/usr/bin/time -o results.md -f '|Jest all tests|%e|%U|%S|' -a ./node_modules/.bin/jest --silent --testRegex 'build/jest' 2>&1 > /dev/null
echo ''

echo "${bold}Jest single test...${normal}"
/usr/bin/time -o results.md -f '|Jest single test|%e|%U|%S|' -a ./node_modules/.bin/jest --silent --testRegex 'build/jest/SailsTest.js' 2>&1 > /dev/null
echo ''

echo "${bold}${teal}************* Mocha *************${normal}"
echo -n "${bold}Mocha all tests...${normal}"
/usr/bin/time -o results.md -f '|Mocha all tests|%e|%U|%S|' -a ./node_modules/.bin/mocha build/mocha/*Test.js 2>&1 > /dev/null
echo ''

echo -n "${bold}Mocha single test...${normal}"
/usr/bin/time -o results.md -f '|Mocha single test|%e|%U|%S|' -a ./node_modules/.bin/mocha build/mocha/SailsTest.js 2>&1 > /dev/null
echo ''

echo "${bold}${teal}************* Tape *************${normal}"
echo -n "${bold}Tape all tests...${normal}"
/usr/bin/time -o results.md -f '|Tape all tests|%e|%U|%S|' -a ./node_modules/.bin/tape build/tape/*Test.js 2>&1 > /dev/null
echo ''

echo -n "${bold}Tape single test...${normal}"
/usr/bin/time -o results.md -f '|Tape single test|%e|%U|%S|' -a ./node_modules/.bin/tape build/tape/SailsTest.js 2>&1 > /dev/null
echo ''

echo "${bold}${teal}************* Uvu *************${normal}"
echo -n "${bold}Uvu all tests...${normal}"
/usr/bin/time -o results.md -f '|Uvu all tests|%e|%U|%S|' -a ./node_modules/.bin/uvu build/uvu 2>&1 > /dev/null
echo ''

echo -n "${bold}Uvu single test...${normal}"
/usr/bin/time -o results.md -f '|Uvu single test|%e|%U|%S|' -a node build/uvu/SailsTest.js 2>&1 > /dev/null
echo ''

echo "${bold}${teal}************* Donc *************${normal}"
echo -n "${bold}Donc all tests...${normal}"
/usr/bin/time -o results.md -f '|Donc all tests|%e|%U|%S|' -a ./node_modules/.bin/donc build/donc/*Test.js 2>&1 > /dev/null
echo ''

echo -n "${bold}Donc single test...${normal}"
/usr/bin/time -o results.md -f '|Donc single test|%e|%U|%S|' -a ./node_modules/.bin/donc build/donc/SailsTest.js 2>&1 > /dev/null
echo ''

echo "${bold}${teal}************* Banana-shark *************${normal}"
echo -n "${bold}Banana-shark all tests...${normal}"
/usr/bin/time -o results.md -f '|Banana-shark all tests|%e|%U|%S|' -a ./node_modules/.bin/bs build/banana-shark/*Test.js 2>&1 > /dev/null
echo ''

echo -n "${bold}Banana-shark single test...${normal}"
/usr/bin/time -o results.md -f '|Banana-shark single test|%e|%U|%S|' -a ./node_modules/.bin/bs build/banana-shark/SailsTest.js 2>&1 > /dev/null
echo ''

echo "${bold}${teal}Node start up time${normal}"
/usr/bin/time -o results.md -f '|Node start up time|%e|%U|%S|' -a node -e 1
